2024-02-27 20:14:56.542 [info] (Client) Pylance async client (2024.2.2) started with python extension (2024.0.1)
2024-02-27 20:14:59.827 [info] [Info  - 20:14:59] (166813) Pylance language server 2024.2.2 (pyright version 1.1.348, commit cfb1de0c) starting
2024-02-27 20:14:59.830 [info] [Info  - 20:14:59] (166813) Server root directory: file:///home/daniel/.vscode/extensions/ms-python.vscode-pylance-2024.2.2/dist
2024-02-27 20:14:59.830 [info] [Info  - 20:14:59] (166813) Starting service instance "3_django"
2024-02-27 20:15:00.188 [info] [Info  - 20:15:00] (166813) Setting pythonPath for service "3_django": "/home/daniel/Documentos/repos/Harvard-Web-Python-Javascript/3_django/env/bin/python"
2024-02-27 20:15:00.189 [info] [Info  - 20:15:00] (166813) Setting environmentName for service "3_django": "3.11.2 (env venv)"
2024-02-27 20:15:00.422 [info] [Info  - 20:15:00] (166813) Assuming Python version 3.11
2024-02-27 20:15:00.715 [info] [Info  - 20:15:00] (166813) Auto-excluding /home/daniel/Documentos/repos/Harvard-Web-Python-Javascript/3_django/env
2024-02-27 20:15:00.759 [info] [Info  - 20:15:00] (166813) Found 22 source files
2024-02-27 20:15:02.101 [info] [Info  - 20:15:02] (166813) Background analysis(1) root directory: file:///home/daniel/.vscode/extensions/ms-python.vscode-pylance-2024.2.2/dist
2024-02-27 20:15:02.114 [info] [Info  - 20:15:02] (166813) Background analysis(1) started
2024-02-27 20:16:41.388 [info] [Error - 20:16:41] Server process exited with code 0.
